use std::fs;
use std::net::TcpListener;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::thread::sleep;
use std::time::{Duration, Instant};

use serde_json::{Value, json};
use tempfile::TempDir;

/*
 * These tests drive the real mirai-agent binary against a fake HOME, so they
 * pin what the hub sees in /metrics and nothing about how the agent gets there.
 * fc-match is a stub on PATH that logs every call, which is how the tests see
 * whether the font is re-read.
 */

const TOKYO_NIGHT: &str = r##"# Generated by Aether for Omarchy v4.
mode = "dark"

accent = "#7aa2f7"
selection = "#292e42"
muted = "#565f89"

cursor = "#c0caf5"

background = "#1a1b26"
dark_background = "#16161e"
foreground = "#A9B1D6"
dark_foreground = "#565f89"

red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
orange = "#eb927b"
bright_blue = "#7da6ff"
bright_magenta = "#bb9af7"
bright_cyan = "#0db9d7"
brown = "#75493d"
bright_red = "#ff7a93"
bright_green = "#b9f27c"

# A key Mirai has never heard of still travels as-is.
zz_custom_tint = "#123456"
"##;

/* Every `key = "value"` line of a colors.toml except mode, which is reported separately. */
fn color_keys(toml: &str) -> serde_json::Map<String, Value> {
    toml.lines()
        .filter_map(|l| l.split_once('='))
        .map(|(k, v)| (k.trim().to_string(), v.trim().trim_matches('"').to_string()))
        .filter(|(k, _)| !k.starts_with('#') && k != "mode")
        .map(|(k, v)| (k, json!(v)))
        .collect()
}

const CATPPUCCIN_LATTE: &str = r##"mode = "light"
accent = "#1e66f5"
background = "#eff1f5"
foreground = "#4c4f69"
"##;

struct Agent {
    child: Child,
    base: String,
    home: TempDir,
    _bin: TempDir,
    fc_log: PathBuf,
    fc_out: PathBuf,
}

impl Drop for Agent {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

fn free_port() -> u16 {
    TcpListener::bind("127.0.0.1:0").and_then(|l| l.local_addr()).map(|a| a.port()).expect("a free local port")
}

fn theme_file(home: &Path) -> PathBuf {
    home.join(".local/state/omarchy/current/theme/colors.toml")
}

fn write(path: &Path, body: &str) {
    fs::create_dir_all(path.parent().expect("path has a parent")).expect("create parent dirs");
    fs::write(path, body).expect("write file");
}

fn start(colors: Option<&str>) -> Agent {
    let home = tempfile::tempdir().expect("temp home");
    let bin = tempfile::tempdir().expect("temp bin");
    if let Some(body) = colors {
        write(&theme_file(home.path()), body);
    }
    write(&home.path().join(".config/fontconfig/fonts.conf"), "<fontconfig><match><edit name=\"family\"><string>Fake Mono Nerd Font</string></edit></match></fontconfig>\n");
    let fc_log = bin.path().join("fc-match.log");
    let fc_out = bin.path().join("fc-match.out");
    fs::write(&fc_out, "Fake Mono Nerd Font,Fake Mono NF\n").expect("write fc-match output");
    let script = bin.path().join("fc-match");
    fs::write(&script, format!("#!/bin/sh\necho \"$@\" >> '{}'\ncat '{}'\n", fc_log.display(), fc_out.display())).expect("write fc-match stub");
    fs::set_permissions(&script, fs::Permissions::from_mode(0o755)).expect("chmod fc-match stub");

    let port = free_port();
    let path = format!("{}:{}", bin.path().display(), std::env::var("PATH").unwrap_or_else(|_| "/usr/bin:/bin".into()));
    let child = Command::new(env!("CARGO_BIN_EXE_mirai-agent"))
        .env_clear()
        .env("HOME", home.path())
        .env("PATH", path)
        .env("TAILSCALE_BIN", "/usr/bin/false")
        .env("MIRAI_AGENT_HOST", "127.0.0.1")
        .env("MIRAI_AGENT_PORT", port.to_string())
        .env("MIRAI_AGENT_SAMPLE_CACHE_MS", "100")
        .env("MIRAI_AGENT_PROJECTS_ROOT", home.path().join("Developer"))
        .env("DOCKER_HOST", format!("unix://{}", home.path().join("docker.sock").display()))
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .expect("spawn mirai-agent");
    let agent = Agent { child, base: format!("http://127.0.0.1:{port}"), home, _bin: bin, fc_log, fc_out };
    let deadline = Instant::now() + Duration::from_secs(15);
    while Instant::now() < deadline {
        if ureq::get(format!("{}/health", agent.base)).call().is_ok() {
            return agent;
        }
        sleep(Duration::from_millis(100));
    }
    panic!("mirai-agent did not come up on {}", agent.base);
}

fn metrics(agent: &Agent) -> Value {
    let body = ureq::get(format!("{}/metrics", agent.base)).call().expect("GET /metrics").body_mut().read_to_string().expect("read /metrics body");
    serde_json::from_str(&body).expect("/metrics is JSON")
}

fn eventually(agent: &Agent, within: Duration, done: impl Fn(&Value) -> bool) -> Value {
    let deadline = Instant::now() + within;
    loop {
        let m = metrics(agent);
        if done(&m) || Instant::now() >= deadline {
            return m;
        }
        sleep(Duration::from_millis(200));
    }
}

fn fc_calls(agent: &Agent) -> usize {
    fs::read_to_string(&agent.fc_log).map(|s| s.lines().count()).unwrap_or(0)
}

#[test]
fn the_omarchy_theme_and_the_first_monospace_family_land_in_the_report() {
    let agent = start(Some(TOKYO_NIGHT));
    let system = &metrics(&agent)["system"];
    assert_eq!(system["mode"], json!("dark"));
    assert_eq!(system["monoFont"], json!("Fake Mono Nerd Font"));
    let mut colors = system["colors"].as_object().expect("system.colors is an object").clone();
    colors.remove("mode");
    assert_eq!(colors, color_keys(TOKYO_NIGHT), "colors carries every colors.toml key and value as-is, including ones Mirai does not map");
    assert_eq!(colors.get("foreground"), Some(&json!("#A9B1D6")), "values keep their case");
}

#[test]
fn a_light_theme_reports_light_mode() {
    let agent = start(Some(CATPPUCCIN_LATTE));
    let system = &metrics(&agent)["system"];
    assert_eq!(system["mode"], json!("light"));
    let mut colors = system["colors"].as_object().expect("system.colors is an object").clone();
    colors.remove("mode");
    assert_eq!(colors, color_keys(CATPPUCCIN_LATTE));
}

#[test]
fn without_a_theme_file_the_report_has_no_system_key_at_all() {
    let agent = start(None);
    let report = metrics(&agent);
    assert!(report.get("cpu").is_some(), "the rest of the report is still there");
    assert!(report.get("system").is_none(), "system is absent, not null: {:?}", report.get("system"));
}

#[test]
fn switching_the_theme_reaches_the_report_without_restarting_the_agent() {
    let agent = start(Some(TOKYO_NIGHT));
    assert_eq!(metrics(&agent)["system"]["colors"]["background"], json!("#1a1b26"));
    write(&theme_file(agent.home.path()), CATPPUCCIN_LATTE);
    let after = eventually(&agent, Duration::from_secs(15), |m| m["system"]["mode"] == json!("light"));
    assert_eq!(after["system"]["mode"], json!("light"));
    assert_eq!(after["system"]["colors"]["background"], json!("#eff1f5"));
}

#[test]
fn removing_the_theme_file_drops_system_from_later_reports() {
    let agent = start(Some(TOKYO_NIGHT));
    assert!(metrics(&agent).get("system").is_some());
    fs::remove_file(theme_file(agent.home.path())).expect("remove colors.toml");
    let after = eventually(&agent, Duration::from_secs(15), |m| m.get("system").is_none());
    assert!(after.get("system").is_none());
}

#[test]
fn the_font_is_read_once_and_again_only_after_fontconfig_changes() {
    let agent = start(Some(TOKYO_NIGHT));
    for _ in 0..5 {
        assert_eq!(metrics(&agent)["system"]["monoFont"], json!("Fake Mono Nerd Font"));
        sleep(Duration::from_millis(150));
    }
    assert_eq!(fc_calls(&agent), 1, "fc-match runs once while fontconfig is unchanged");

    sleep(Duration::from_millis(1100));
    fs::write(&agent.fc_out, "Other Mono,Other Mono Alias\n").expect("change fc-match output");
    write(&agent.home.path().join(".config/fontconfig/fonts.conf"), "<fontconfig><match><edit name=\"family\"><string>Other Mono</string></edit></match></fontconfig>\n");
    let after = eventually(&agent, Duration::from_secs(15), |m| m["system"]["monoFont"] == json!("Other Mono"));
    assert_eq!(after["system"]["monoFont"], json!("Other Mono"), "a fontconfig change is picked up");
}
